# .github/workflows/monitor.yml

name: Drift Monitoring

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily, adjust as needed

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Make sure to list your dependencies
        python -m pip install --upgrade pip

    - name: Run monitoring script
      run: python monitoring_script.py
